services:
  - type: web
    name: mizan-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    region: singapore

    healthCheckPath: /api/actuator/health

    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: JWT_REFRESH_EXPIRATION
        value: "604800000"
      - key: CORS_ORIGINS
        value: https://frontend-drab-zeta-35.vercel.app,http://localhost:4200
      - key: LOG_LEVEL
        value: INFO
